data:
  train_path: "/data/npl/Speech2Text/RNN-Transducer/data/train.csv"
  val_path: "/data/npl/Speech2Text/RNN-Transducer/data/test.csv"
  seed: 123456
  num_workers: 4
  batch_size: 4
  

audio_data:
  type: "log"
  sampling_rate: 16000
  window_size: 0.02
  window_stride: 0.01
  window: 'hamming'

model:
  enc:
    type: lstm
    input_size: 161
    hidden_size: 1024
    output_size: 320
    n_layers: 6
    bidirectional: False
  dec:
    type: lstm
    embedding_size: 128
    hidden_size: 1024
    output_size: 320
    n_layers: 2
  joint:
    input_size: 640
    inner_dim: 320

  vocab_size: 99
  feature_dim: 160
  dropout: 0.3

training:
  begin_epoch: 0
  end_epoch: 100

optim:
  type: "AdamW"
  lr: 0.00001110889
  weight_decay: 0.01
  milestones: [7, 14]
  decay_rate: 0.3333

loss:
  reduction: "mean"
  blank_id: 0
  gather: True