training:
  epochs: 100
  batch_size: 1
  save_path: "/home/anhkhoa/transformer_transducer/save_folder_new"
  train_path : "/home/anhkhoa/transformer_transducer/data/train.json"
  dev_path : "/home/anhkhoa/transformer_transducer/data/dev.json"
  test_path : "/home/anhkhoa/transformer_transducer/data/test.json"
  vocab_path : "/home/anhkhoa/transformer_transducer/data/vocab.json"
  reload: False
  


optimizer:
  name: Adam
  lr: 0.0005
  weight_decay: 0.0001


model:
  in_features: 80
  n_layers: 18
  n_dec_layers: 2
  d_model: 512
  ff_size: 2048
  h: 8
  joint_size: 512
  enc_left_size: 10
  enc_right_size: 0
  dec_left_size: 20
  dec_right_size: 0
  p_dropout: 0.1
  model_name: "transformer_transducer"



rnnt_loss:
  blank: 4
  reduction: "mean" 


